# Generated by Django 4.2.13 on 2024-07-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('min_len', models.SmallIntegerField(default=1)),
                ('url_end_point', models.CharField(max_length=100)),
                ('is_serie', models.BooleanField(default=False)),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
    ]
